name: "Run ECS task"
description: "Run task in context of a service"
inputs:
  cluster:
    description: "ECS cluster to run task in"
    required: true
  service:
    description: "ECS service to read parameters from"
    required: true
  container:
    description: "ECS container in task (if task contain more, than one)"
    required: false
  task-definition:
    description: "ECS task definition ARN"
    required: false
  show-raw-output:
    description: "Display task logs"
    default: false

outputs:
  console_url:
    description: "URL of task page in AWS console"
  raw_output:
    description: "Raw output from task"

runs:
  using: "node12"
  main: "dist/index.js"
